BOARD=eaie-v1-riscv-spacemitk1
KERNEL_REBUILD=no
UBOOT_REBUILD=no
FULL_CLEAN=no
SOURCE_ORIGIN=custom
EAIE_CUSTOM_KERNEL_SOURCE_URL=git@github.com:gslm/linux-6.6-spacemit-k1.git
EAIE_CUSTOM_KERNEL_SOURCE_REF=eaie-v1-riscv-spacemitk1
EAIE_CUSTOM_UBOOT_SOURCE_URL=git@github.com:gslm/uboot-2022.10-spacemit-k1.git
EAIE_CUSTOM_UBOOT_SOURCE_REF=eaie-v1-riscv-spacemitk1

BOARD_HOST=192.168.28.85
BOARD_USER=eaie
BOARD_PASS=eaie
BOARD_SSH_PORT=22
AUTO_REBOOT=yes
